request functionality added, test for all app added
GurevVikrot/java-shareit pull request #3
Opened 2022-09-08 21:32 UTC by GurevVikrot

2022-09-09 20:33 UTC, SnikerZi requested changes
Ты молодец, но необходимо немного поправить код. В основном струтура кода почти правильная, но есть пара замечаний. К базе данных вопросов, вроде, нет.

2022-09-09 20:33 UTC, SnikerZi commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +import ru.practicum.shareit.booking.status.BookingStatus;
У тебя не хватает конструктора для подкласса booker и item

2022-09-09 20:33 UTC, SnikerZi commented on src/main/java/ru/practicum/shareit/booking/dto/RequestBookingDto.java
> +@NoArgsConstructor
Не хватает декоратора StartBeforeEndValid

2022-09-09 20:33 UTC, SnikerZi commented on src/main/java/ru/practicum/shareit/booking/dto/ResponseBookingDto.java
> +@NoArgsConstructor
Вместо Data я рекомендую использовать Getter

2022-09-09 20:33 UTC, SnikerZi commented on src/main/java/ru/practicum/shareit/booking/mapper/DefaultBookingMapper.java
> +import ru.practicum.shareit.booking.model.Booking;
У тебя не хватает метода, который будет создавать BookingDto из Booking

2022-09-09 20:33 UTC, SnikerZi commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +import ru.practicum.shareit.booking.status.BookingStatus;
У полей start и end должен быть аргумент  nullable = false , также у enum'a @Column(name = "status", nullable = false)

2022-09-09 20:33 UTC, SnikerZi commented on src/main/java/ru/practicum/shareit/booking/status/State.java
> +package ru.practicum.shareit.booking.status;
Тут стоит добавить метод
public static Optional<BookingState> from(String stringState) {
for (BookingState state : values()) {
if (state.name().equalsIgnoreCase(stringState)) {
return Optional.of(state);
}
}
return Optional.empty();
}

2022-09-11 13:25 UTC, GurevVikrot commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +import ru.practicum.shareit.booking.status.BookingStatus;
Добавил nulable = false во всех Entity и модернизировал schema NOT NULL, везде где обязательны поля.
В entity мы указываем эту доп информацию, чтобы отловить ошибку раньше, не пропуская ее в БД?

2022-09-11 13:32 UTC, GurevVikrot commented on src/main/java/ru/practicum/shareit/booking/mapper/DefaultBookingMapper.java
> +import ru.practicum.shareit.booking.model.Booking;
Он есть, ниже на 24 строчке:
`  @Override
    public BookingDto toItemBooking(Booking booking) {
        return new BookingDto(booking.getId(),
                booking.getStart(),
                booking.getEnd(),
                userMapper.toUserDto(booking.getBooker()).getId(),
                booking.getStatus());
    }`

2022-09-11 13:35 UTC, GurevVikrot commented on src/main/java/ru/practicum/shareit/booking/mapper/DefaultBookingMapper.java
> +import ru.practicum.shareit.booking.model.Booking;
Возможно ты имел ввиду обратное преобразование BookingDto -> Booking
Его нет т.к. BookingDto используется только в формировании ответа на запрос Item владельцем с указанием последнего и следующего бронирования через BookingDto

2022-09-11 13:45 UTC, GurevVikrot commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +import ru.practicum.shareit.booking.status.BookingStatus;
Не понял. Можешь уточнить? 
Если имеешь ввиду, что BookingDto должен содержать поля ItemDto и UserDto, то объясню:
BookingDto используется только при запросе вещи/вещей владельца для указания последнего и следующего бронирования. В нем, как я думаю, не нужна подробная инфа о бронирующем и достаточно его id, а информация о вещи содержится в самом классе владеющем полем BookingDto.
При работе с бронированиями непосредственно, для ответа используется ResponseBookingDto, в нем уже есть поля UserDto и ItemDto

2022-09-11 14:45 UTC, GurevVikrot commented on src/main/java/ru/practicum/shareit/booking/dto/ResponseBookingDto.java
> +@NoArgsConstructor
Почему? Ведь Data включает в себя Getter. Плюс в уменьшении генерируемых методов? Но Data позволяет также не тратить время на hashCode, equals, toString, а если нам потребуется не стандартная логика в этих методах, то мы их напишем и lombok не сгенерирует свои с таким же именем

2022-09-11 14:48 UTC, GurevVikrot commented on src/main/java/ru/practicum/shareit/booking/dto/RequestBookingDto.java
> +@NoArgsConstructor
Не понял, информации не нашел. Это аннотация?
Нашел инфо только по паттерну проектирования - декоратор, но не вижу где его можно применить в этом проекте. Если только между RequestBookingDto и BookingDto

2022-09-11 15:38 UTC, GurevVikrot commented on src/main/java/ru/practicum/shareit/booking/status/State.java
> +package ru.practicum.shareit.booking.status;
Spring выдает исключение MethodArgumentTypeMismatchException, если получает запрос со стрингом, который невозможно сопоставить ни с одним enum. Действительно нужна эта логика с преобразованием через отдельный метод? По сути это будет лишний код, до которого даже не дойдет работа, ведь спринг отловит исключение раньше, при преобразовании json в dto ну или других переменных в их java представление

2022-09-12 13:31 UTC, SnikerZi commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +import ru.practicum.shareit.booking.status.BookingStatus;
Тут я имел ввиду, что в авторском решении данной задачи содержатся методы для создания Booker и Item (которые, скорее всего, пока не нужны в данном решении и понадобятся в следующем задании) , которые возвращают структуру с id и одним полем, дающим идентифицировать нужного нам человека/ предмет.
Однако при детальном рассмотрении твоего решения твой подход также является правильным, однако в review на гите нельзя пометить комментарий как совет, в будущем необязательные комментарии буду помечать в конце как совет.

2022-09-12 13:34 UTC, SnikerZi commented on src/main/java/ru/practicum/shareit/booking/dto/RequestBookingDto.java
> +@NoArgsConstructor
Это аннотация спринга, для валидации. Документацию можно найти на сайте спринга

2022-09-12 13:36 UTC, SnikerZi commented on src/main/java/ru/practicum/shareit/booking/dto/ResponseBookingDto.java
> +@NoArgsConstructor
В данной задаче лучше уменьшить количество генерируемых методов. Также пока нет необходимости переопределять hashCode, equals, toString, потому что эти методы не используются.

2022-09-12 13:38 UTC, SnikerZi commented on src/main/java/ru/practicum/shareit/booking/mapper/DefaultBookingMapper.java
> +import ru.practicum.shareit.booking.model.Booking;
Метод, создающий Booking из BookingDto понадобится в следующей работе, поэтому этот комментарий лишь совет по улучшению кода.

2022-09-12 13:39 UTC, SnikerZi commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +import ru.practicum.shareit.booking.status.BookingStatus;
Твоя логика верная, это оптимизирует нагрузку на сервер и не допускает вызова следующих методов на этом этапе.

2022-09-12 13:41 UTC, SnikerZi commented on src/main/java/ru/practicum/shareit/booking/status/State.java
> +package ru.practicum.shareit.booking.status;
Этот метод даёт более читабельный код, тк при просмотре кода сложно сразу понять, что до этого момента может подняться  исключение, которое не даст запуститься этому коду.

2022-09-12 18:50 UTC, SnikerZi approved these changes
Спасибо за правки, у тебя отлично получилось.

2022-09-12 19:53 UTC, merged